(() => {
  'use strict';
  const $ = s => document.querySelector(s);
  const canvas = $('#game'), ctx = canvas.getContext('2d');
  const screens = { title: $('#title-screen'), game: $('#game-screen'), talents: $('#talent-screen') };
  const SAVE_KEY = 'morgan-mage-arena-v1';
  const save = Object.assign({level:1,xp:0,points:0,talents:{power:0,mana:0,vitality:0,haste:0},spellTalents:{golem:0,vortex:0,vines:0,teleport:0},bestWave:0,kills:0}, JSON.parse(localStorage.getItem(SAVE_KEY)||'{}'));
  save.talents = Object.assign({power:0,mana:0,vitality:0,haste:0},save.talents||{});
  save.spellTalents = Object.assign({golem:0,vortex:0,vines:0,teleport:0},save.spellTalents||{});
  let audio, state, raf, last=0, selectedArena='colosseum';
  const mouse={x:640,y:360,down:false,charge:0,vineDraw:null}; const keys={};
  const rnd=(a,b)=>a+Math.random()*(b-a), clamp=(n,a,b)=>Math.max(a,Math.min(b,n)), dist=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y);
  function persist(){localStorage.setItem(SAVE_KEY,JSON.stringify(save)); updateMeta();}
  function xpNeed(){return 80+save.level*35;}
  function addXP(n){save.xp+=n; while(save.xp>=xpNeed()){save.xp-=xpNeed();save.level++;save.points++; tone(660,.15,'triangle');} persist();}
  function updateMeta(){
    $('#points-badge').textContent=`${save.points} point${save.points===1?'':'s'}`;
    $('#talent-summary').textContent=`Level ${save.level} · ${save.points} perk point${save.points===1?'':'s'} available`;
    document.querySelectorAll('.talent[data-talent]').forEach(el=>{const v=save.talents[el.dataset.talent];el.querySelector('i').textContent=`${v} / 3`;el.classList.toggle('maxed',v>=3)});
    document.querySelectorAll('.spell-talent').forEach(el=>{const v=save.spellTalents[el.dataset.spellTalent];el.querySelector('i').textContent=`${v} / 3`;el.classList.toggle('maxed',v>=3)});
    document.querySelectorAll('.future-slot').forEach(el=>{const open=save.level>=Number(el.dataset.unlock);el.classList.toggle('unlocked',open);el.classList.toggle('locked',!open);el.querySelector('span').textContent=open?'Empty':`Level ${el.dataset.unlock}`;el.querySelector('b').textContent=open?'◇':'?'});
  }
  function show(name){Object.values(screens).forEach(s=>s.classList.remove('active'));screens[name].classList.add('active');}
  function tone(freq,d=.08,type='sine',vol=.055){try{audio ||= new (window.AudioContext||window.webkitAudioContext)(); const o=audio.createOscillator(),g=audio.createGain();o.type=type;o.frequency.setValueAtTime(freq,audio.currentTime);g.gain.setValueAtTime(vol,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+d);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+d)}catch(e){}}
  function resize(){const r=canvas.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,2);canvas.width=r.width*d;canvas.height=r.height*d;ctx.setTransform(d,0,0,d,0,0);if(state){state.w=r.width;state.h=r.height}}
  function start(){
    $('#pause-menu').classList.add('hidden');$('#pause-button').textContent='Ⅱ';show('game');resize();
    const mh=100+save.talents.vitality*20, mm=100+save.talents.mana*20;
    state={w:canvas.clientWidth,h:canvas.clientHeight,arena:selectedArena,time:0,paused:false,over:false,wave:1,waveDelay:1.5,spawned:0,toSpawn:6,kills:0,projectiles:[],enemies:[],particles:[],effects:[],vines:[],golems:[],focus:null,
      player:{x:canvas.clientWidth/2,y:canvas.clientHeight/2,r:22,hp:mh,maxHp:mh,armor:0,maxArmor:0,mana:mm,maxMana:mm,speed:230,shield:0,parry:0,invuln:0,moving:false,attackAnim:0,castAnim:0,cool:{golem:0,vortex:0,vines:0,teleport:0,shield:0}}};
    mouse.down=false;mouse.charge=0;last=performance.now();cancelAnimationFrame(raf);raf=requestAnimationFrame(loop);
  }
  function spawnEnemy(){
    const edge=Math.floor(Math.random()*4), pad=55; let x,y;if(edge<2){x=edge?state.w+pad:-pad;y=rnd(90,state.h-70)}else{x=rnd(50,state.w-50);y=edge===2?-pad:state.h+pad}
    const boss=state.wave===10&&state.spawned===state.toSpawn-1,captain=!boss&&state.wave>=5&&state.spawned===state.toSpawn-1,hp=boss?520:captain?170:45+state.wave*10;
    state.enemies.push({x,y,r:boss?34:captain?25:18,hp,maxHp:hp,speed:boss?42:captain?48:55+state.wave*2,damage:boss?25:captain?18:9+Math.floor(state.wave/3),type:boss?'champion':captain?'captain':state.arena==='colosseum'?'soldier':'skeleton',hit:0,attack:0,attackAnim:0,windup:0,striking:false,moving:false,slow:0,knockX:0,knockY:0,knockTime:0});state.spawned++;
  }
  function castFocus(kind){if(state.over||state.paused)return; const p=state.player;if(p.cool[kind]>0)return; const cost=kind==='golem'?35:kind==='vines'?16:28;if(p.mana<cost){tone(120,.12,'square');return}state.focus=kind;p.castAnim=.35;$('#focus-help').textContent=kind==='vines'?'Click and drag to grow a vine wall · Release to cast · Right-click to cancel':'Move the sigil · Click to cast · Right-click to cancel';$('#focus-help').classList.remove('hidden');document.querySelector(`[data-spell="${kind}"]`).classList.add('active');tone(440,.12,'sine')}
  function confirmFocus(){if(!state.focus||state.focus==='vines')return;const kind=state.focus,p=state.player,mastery=save.spellTalents[kind]||0;p.castAnim=.65;if(kind==='golem'){p.mana-=35;p.cool.golem=12;state.golems.push({x:mouse.x,y:mouse.y,r:25,hp:180*(1+mastery*.25),time:14*(1+mastery*.25),attack:0,attackAnim:0,moving:false,summon:.7});burst(mouse.x,mouse.y,'#c7a4ff',22)}else{p.mana-=28;p.cool.vortex=8;state.effects.push({type:'vortex',x:mouse.x,y:mouse.y,r:115+mastery*12,time:4+mastery*.5,power:9+mastery*4});burst(mouse.x,mouse.y,'#b474ff',28)}cancelFocus();tone(kind==='golem'?180:280,.3,'sawtooth')}
  function finishVines(points){if(!state||points.length<2){mouse.vineDraw=null;return}const p=state.player,mastery=save.spellTalents.vines||0,spaced=[];for(const pt of points){if(!spaced.length||dist(pt,spaced[spaced.length-1])>18)spaced.push(pt)}const capped=spaced.slice(0,18),cost=12+capped.length*1.15;if(p.mana<cost){tone(120,.12,'square');mouse.vineDraw=null;cancelFocus();return}p.mana-=cost;p.cool.vines=7;p.castAnim=.7;state.vines.push({points:capped,hp:90+mastery*45,maxHp:90+mastery*45,time:14+mastery*2,hit:0});capped.forEach((pt,i)=>{if(i%2===0)burst(pt.x,pt.y,'#66b85c',4)});mouse.vineDraw=null;cancelFocus();tone(220,.3,'sawtooth')}
  function cancelFocus(){if(state?.focus)document.querySelector(`[data-spell="${state.focus}"]`)?.classList.remove('active');if(state)state.focus=null;mouse.vineDraw=null;$('#focus-help').classList.add('hidden')}
  function startShield(){const p=state.player;if(p.mana<4||p.shield)return;p.shield=1;p.parry=.24;p.castAnim=.35;tone(720,.18,'sine');burst(p.x,p.y,'#69dfff',12)}
  function endShield(){if(state?.player)state.player.shield=0}
  function castTeleport(){const p=state.player;if(p.cool.teleport||p.mana<18)return;let dx=mouse.x-p.x,dy=mouse.y-p.y,d=Math.hypot(dx,dy)||1,range=Math.min(190+save.spellTalents.teleport*25,d);burst(p.x,p.y,'#9f7cff',14);p.x=clamp(p.x+dx/d*range,35,state.w-35);p.y=clamp(p.y+dy/d*range,80,state.h-45);burst(p.x,p.y,'#f1d27a',18);p.mana-=18;p.cool.teleport=4/(1+save.spellTalents.teleport*.1);p.invuln=.25;p.castAnim=.4;tone(880,.18,'triangle')}
  function shoot(){const p=state.player,c=clamp(mouse.charge/1.15,0,1),dx=mouse.x-p.x,dy=mouse.y-p.y,d=Math.hypot(dx,dy)||1,cost=3+c*8;if(p.mana<cost)return;const dmg=(13+c*37)*(1+save.talents.power*.15);p.mana-=cost;p.attackAnim=.28;state.projectiles.push({x:p.x+dx/d*25,y:p.y+dy/d*25,vx:dx/d*(550-c*100),vy:dy/d*(550-c*100),r:6+c*9,damage:dmg,time:1.7,color:c>.75?'#ffd465':'#9b8cff'});tone(330+c*300,.08+c*.08,'triangle')}
  function burst(x,y,color,n=8){for(let i=0;i<n;i++){const a=Math.random()*Math.PI*2,s=rnd(30,170);state.particles.push({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s,time:rnd(.25,.7),max:.7,color,r:rnd(2,5)})}}
  function kill(e){addXP(e.type==='champion'?100:e.type==='captain'?35:14);save.kills++;state.kills++;burst(e.x,e.y,e.type==='captain'||e.type==='champion'?'#f3c85d':'#d7d0bf',15);tone(100,.12,'square')}
  function update(dt){
    if(state.paused||state.over)return;state.time+=dt;const p=state.player, slow=state.focus?.12:1,wdt=dt*slow;
    let dx=(keys.KeyD?1:0)-(keys.KeyA?1:0),dy=(keys.KeyS?1:0)-(keys.KeyW?1:0),m=Math.hypot(dx,dy)||1;p.moving=!!(dx||dy);p.x=clamp(p.x+dx/m*p.speed*wdt,28,state.w-28);p.y=clamp(p.y+dy/m*p.speed*wdt,78,state.h-38);
    p.mana=Math.min(p.maxMana,p.mana+(p.shield?0:9)*dt);if(p.shield){p.mana=Math.max(0,p.mana-14*dt);p.parry=Math.max(0,p.parry-dt);if(!keys.KeyQ||p.mana<=0)p.shield=0}p.invuln=Math.max(0,p.invuln-dt);p.attackAnim=Math.max(0,p.attackAnim-dt);p.castAnim=Math.max(0,p.castAnim-dt);Object.keys(p.cool).forEach(k=>p.cool[k]=Math.max(0,p.cool[k]-dt*(1+save.talents.haste*.1)));
    if(mouse.down&&!state.focus)mouse.charge=Math.min(1.2,mouse.charge+dt);
    if(state.spawned<state.toSpawn){state.waveDelay-=dt;if(state.waveDelay<=0){spawnEnemy();state.waveDelay=Math.max(.35,1.15-state.wave*.08)}}
    else if(!state.enemies.length){state.waveDelay-=dt;if(state.waveDelay<=-2){if(state.wave>=10){victory();return}state.wave++;state.spawned=0;state.toSpawn=6+state.wave*2;state.waveDelay=1.3;save.bestWave=Math.max(save.bestWave,state.wave);persist();tone(520,.25,'triangle')}}
    state.effects.forEach(v=>{v.time-=dt;state.enemies.forEach(e=>{const d=dist(v,e);if(d<v.r){e.x+=(v.x-e.x)/Math.max(1,d)*150*wdt;e.y+=(v.y-e.y)/Math.max(1,d)*150*wdt;e.hp-=v.power*dt;e.slow=.15}})});
    state.vines.forEach(v=>{v.time-=dt;v.hit=Math.max(0,v.hit-dt)});
    state.golems.forEach(g=>{g.time-=dt;g.attack-=dt;g.attackAnim=Math.max(0,g.attackAnim-dt);g.summon=Math.max(0,g.summon-dt);let target=state.enemies.reduce((a,e)=>!a||dist(g,e)<dist(g,a)?e:a,null);g.moving=false;if(target){let d=dist(g,target),gx=(target.x-g.x)/d,gy=(target.y-g.y)/d;if(d>48){g.moving=true;g.x+=gx*75*wdt;g.y+=gy*75*wdt}else if(g.attack<=0){target.hp-=24;target.hit=.15;g.attack=1;g.attackAnim=.45;burst(target.x,target.y,'#bda7cf',8)}}});
    state.projectiles.forEach(b=>{b.x+=b.vx*wdt;b.y+=b.vy*wdt;b.time-=dt;for(const e of state.enemies){if(!b.dead&&dist(b,e)<b.r+e.r){e.hp-=b.damage;e.hit=.12;b.dead=true;burst(b.x,b.y,b.color,7)}}});
    state.enemies.forEach(e=>{e.hit=Math.max(0,e.hit-dt);e.attack-=dt;e.attackAnim=Math.max(0,e.attackAnim-dt);e.slow=Math.max(0,e.slow-dt);if(e.knockTime>0){e.x+=e.knockX*dt;e.y+=e.knockY*dt;e.knockTime-=dt;return}let target=p,td=dist(e,p);for(const g of state.golems){const gd=dist(e,g);if(gd<td*1.3){target=g;td=gd}}let ex=(target.x-e.x)/(td||1),ey=(target.y-e.y)/(td||1),blocking=null;if(target===p){for(const v of state.vines){for(const pt of v.points){if(Math.hypot(e.x+ex*18-pt.x,e.y+ey*18-pt.y)<e.r+13){blocking=v;break}}if(blocking)break}}if(blocking){target=blocking;td=0;e.moving=false}else e.moving=td>e.r+(target.r||10)+5;if(e.striking){e.moving=false;e.windup-=dt;if(e.windup<=0){e.striking=false;e.attack=e.type==='champion'?1.25:e.type==='captain'?1.1:.78;e.attackAnim=.32;if(target===p){const aim=Math.atan2(mouse.y-p.y,mouse.x-p.x),incoming=Math.atan2(e.y-p.y,e.x-p.x),front=Math.abs(Math.atan2(Math.sin(incoming-aim),Math.cos(incoming-aim)))<=Math.PI/2;if(p.shield&&front){if(p.parry>0){p.parry=0;state.enemies.forEach(n=>{const nd=dist(n,p);if(nd<125){n.hp-=32;const nx=(n.x-p.x)/(nd||1),ny=(n.y-p.y)/(nd||1);n.knockX=nx*360;n.knockY=ny*360;n.knockTime=.28}});burst(p.x,p.y,'#b9f5ff',30);tone(1100,.18,'triangle')}else{burst(p.x,p.y,'#6ee8ff',8);tone(900,.08,'sine')}}else if(!p.invuln){let damage=e.damage;if(p.armor>0){const absorbed=Math.min(p.armor,damage);p.armor-=absorbed;damage-=absorbed}p.hp-=damage;p.invuln=.35;burst(p.x,p.y,'#e34b62',6);tone(85,.18,'sawtooth')}}else if(target.points){target.hp-=e.damage;target.hit=.18;burst(e.x,e.y,'#5d9d4b',5)}else target.hp-=e.damage}}else if(e.moving){const snared=e.slow>0;e.x+=ex*e.speed*(snared?.18:1)*wdt;e.y+=ey*e.speed*(snared?.18:1)*wdt}else if(e.attack<=0){e.striking=true;e.windup=e.type==='champion'?.7:e.type==='captain'?.55:.38}});
    state.particles.forEach(q=>{q.x+=q.vx*dt;q.y+=q.vy*dt;q.vx*=.93;q.vy*=.93;q.time-=dt});
    state.projectiles=state.projectiles.filter(b=>b.time>0&&!b.dead);state.effects=state.effects.filter(v=>v.time>0);state.vines=state.vines.filter(v=>v.time>0&&v.hp>0);state.golems=state.golems.filter(g=>g.time>0&&g.hp>0);state.particles=state.particles.filter(q=>q.time>0);
    const dead=state.enemies.filter(e=>e.hp<=0);dead.forEach(kill);state.enemies=state.enemies.filter(e=>e.hp>0);
    if(p.hp<=0)defeat();updateHUD();
  }
  function updateHUD(){const p=state.player;$('#health-fill').style.width=`${p.hp/p.maxHp*100}%`;$('#armor-fill').style.width=`${p.maxArmor?p.armor/p.maxArmor*100:0}%`;$('#mana-fill').style.width=`${p.mana/p.maxMana*100}%`;$('#xp-fill').style.width=`${save.xp/xpNeed()*100}%`;$('#health-label').textContent=`${Math.ceil(p.hp)} / ${p.maxHp}`;$('#armor-label').textContent=`${Math.ceil(p.armor)} Armour`;$('#mana-label').textContent=`${Math.floor(p.mana)} / ${p.maxMana}`;$('#xp-label').textContent=`${save.xp} / ${xpNeed()} XP`;$('#level-label').textContent=`Level ${save.level}`;$('#arena-label').textContent=state.arena==='colosseum'?'COLOSSEUM':'GRAVEYARD';$('#wave-label').textContent=`Wave ${state.wave}`;Object.keys(p.cool).forEach(k=>{const el=$(`#cooldown-${k}`);if(el)el.style.transform=`scaleY(${Math.min(1,p.cool[k]/({golem:12,vortex:8,vines:7,shield:6,teleport:4}[k]))})`})}
  function draw(){const w=state.w,h=state.h;ctx.clearRect(0,0,w,h);ctx.fillStyle='#241b34';ctx.fillRect(0,0,w,h);drawGround(w,h);drawArenaFrame(w,h);state.effects.forEach(drawEffect);state.vines.forEach(drawVine);if(mouse.vineDraw)drawVine({points:mouse.vineDraw,hp:1,maxHp:1,preview:true});state.projectiles.forEach(b=>{ctx.save();ctx.shadowBlur=18;ctx.shadowColor=b.color;ctx.fillStyle=b.color;ctx.beginPath();ctx.arc(b.x,b.y,b.r,0,7);ctx.fill();ctx.restore()});state.golems.forEach(drawGolem);state.enemies.forEach(drawEnemy);drawPlayer(state.player);state.particles.forEach(q=>{ctx.globalAlpha=q.time/q.max;ctx.fillStyle=q.color;ctx.beginPath();ctx.arc(q.x,q.y,q.r,0,7);ctx.fill();ctx.globalAlpha=1});if(state.focus&&state.focus!=='vines')drawSigil(mouse.x,mouse.y,state.focus==='vortex'?115:34);if(mouse.down&&!state.focus)drawCharge();}
  function drawGround(w,h){if(state.arena==='colosseum'){ctx.fillStyle='#8e6946';ctx.fillRect(0,0,w,h);for(let y=70;y<h;y+=48){for(let x=0;x<w;x+=64){ctx.fillStyle=((x/64+y/48)%2<1)?'#a77b50':'#9c724a';ctx.fillRect(x,y,63,47)}}ctx.strokeStyle='#e3b96d';ctx.lineWidth=11;ctx.strokeRect(14,72,w-28,h-88);ctx.strokeStyle='#5e3d30';ctx.lineWidth=5;ctx.beginPath();ctx.ellipse(w/2,(h+70)/2,Math.max(160,w*.27),Math.max(110,h*.28),0,0,7);ctx.stroke();for(let i=0;i<12;i++){const x=38+i*(w-76)/11;ctx.fillStyle='#4c3141';ctx.fillRect(x-8,72,16,22);ctx.fillStyle='#e4b751';ctx.beginPath();ctx.arc(x,92,5,0,7);ctx.fill()}}else{ctx.strokeStyle='#332745';ctx.lineWidth=1;for(let x=0;x<w;x+=64){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,h);ctx.stroke()}for(let y=70;y<h;y+=64){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(w,y);ctx.stroke()}for(let i=0;i<14;i++){let x=(i*137+70)%w,y=(i*83+140)%h;ctx.fillStyle='#181223';ctx.fillRect(x-17,y-12,34,24);ctx.fillStyle='#706478';ctx.fillRect(x-13,y-25,26,22);ctx.beginPath();ctx.arc(x,y-25,13,Math.PI,0);ctx.fill();ctx.fillStyle='#4b3a5c';ctx.fillRect(x-2,y-19,4,13);ctx.fillRect(x-7,y-15,14,4)}ctx.strokeStyle='#5c4770';ctx.lineWidth=5;ctx.strokeRect(10,68,w-20,h-78)}}
  function drawArenaFrame(w,h){if(state.arena!=='colosseum')return;ctx.fillStyle='#5d3c35';ctx.fillRect(0,68,w,27);ctx.fillRect(0,h-30,w,30);ctx.fillRect(0,68,34,h-68);ctx.fillRect(w-34,68,34,h-68);ctx.fillStyle='#2b2030';for(let x=48;x<w-48;x+=42){ctx.beginPath();ctx.arc(x,80,7,0,7);ctx.fill();ctx.fillRect(x-6,84,12,8)}ctx.fillStyle='#d9a940';for(let x=90;x<w-80;x+=180){ctx.fillRect(x,70,28,38);ctx.fillStyle='#7d3041';ctx.beginPath();ctx.moveTo(x,108);ctx.lineTo(x+14,125);ctx.lineTo(x+28,108);ctx.fill();ctx.fillStyle='#d9a940'}ctx.fillStyle='#281b25';ctx.fillRect(w/2-56,68,112,28);ctx.strokeStyle='#d8ad5b';ctx.lineWidth=3;for(let x=w/2-46;x<w/2+50;x+=16){ctx.beginPath();ctx.moveTo(x,68);ctx.lineTo(x,96);ctx.stroke()}}
  function drawPlayer(p){ctx.save();const bob=p.moving?Math.sin(state.time*13)*3:Math.sin(state.time*3)*.8,step=p.moving?Math.sin(state.time*13)*4:0,cast=Math.min(1,p.castAnim*3),attack=Math.min(1,p.attackAnim*6),aim=Math.atan2(mouse.y-p.y,mouse.x-p.x);ctx.translate(p.x,p.y+bob);if(p.castAnim){ctx.strokeStyle='#d3aeff';ctx.globalAlpha=cast*.7;ctx.lineWidth=3;ctx.beginPath();ctx.arc(0,0,31+Math.sin(state.time*12)*4,0,7);ctx.stroke();ctx.globalAlpha=1}if(p.shield){ctx.strokeStyle=p.parry>0?'#d8fbff':'#74e6ff';ctx.lineWidth=p.parry>0?8:5;ctx.globalAlpha=.85;ctx.beginPath();ctx.arc(0,0,42+Math.sin(state.time*10)*2,aim-Math.PI/2,aim+Math.PI/2);ctx.stroke();ctx.globalAlpha=1}ctx.fillStyle='#302042';ctx.beginPath();ctx.ellipse(0,18,22,10,0,0,7);ctx.fill();ctx.strokeStyle='#39226c';ctx.lineWidth=6;ctx.beginPath();ctx.moveTo(-8,13);ctx.lineTo(-10-step,25);ctx.moveTo(8,13);ctx.lineTo(10+step,25);ctx.stroke();ctx.fillStyle='#6941bc';ctx.beginPath();ctx.moveTo(-19,16);ctx.lineTo(-13,-12);ctx.lineTo(13,-12);ctx.lineTo(19,16);ctx.closePath();ctx.fill();ctx.fillStyle='#e6ac7e';ctx.beginPath();ctx.arc(0,-13,10,0,7);ctx.fill();ctx.fillStyle='#5d38ad';ctx.beginPath();ctx.moveTo(-21,-17);ctx.lineTo(2,-45);ctx.lineTo(19,-15);ctx.closePath();ctx.fill();ctx.fillStyle='#3f277f';ctx.fillRect(-22,-18,44,7);ctx.strokeStyle='#8a5b32';ctx.lineWidth=5;ctx.beginPath();ctx.moveTo(13,-4);ctx.lineTo(28+attack*10,-33-attack*8-cast*12);ctx.stroke();ctx.fillStyle='#f7d36c';ctx.beginPath();ctx.arc(29+attack*10,-35-attack*8-cast*12,5+cast*3,0,7);ctx.fill();ctx.restore()}
  function drawEnemy(e){ctx.save();const bob=e.moving?Math.sin(state.time*12+e.x)*2.5:0,step=e.moving?Math.sin(state.time*12+e.x)*4:0,swing=Math.min(1,e.attackAnim*7),champ=e.type==='champion';ctx.translate(e.x,e.y+bob);const soldier=e.type==='soldier';ctx.fillStyle=e.hit?'#fff':champ?'#9960b7':e.type==='captain'?'#bda86a':soldier?'#d6a36c':'#d8d4c1';ctx.beginPath();ctx.arc(0,-7,e.r*.68,0,7);ctx.fill();ctx.fillRect(-e.r*.55,2,e.r*1.1,e.r*.8);ctx.fillStyle='#30283a';ctx.beginPath();ctx.arc(-5,-9,3,0,7);ctx.arc(5,-9,3,0,7);ctx.fill();ctx.strokeStyle=soldier?'#7d3d32':'#9a8d73';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(-7,12);ctx.lineTo(-10-step,25);ctx.moveTo(7,12);ctx.lineTo(10+step,25);ctx.stroke();ctx.fillStyle=soldier?'#9b3e39':'#5f4a71';ctx.beginPath();ctx.arc(e.r*.75,4,e.r*.58,0,7);ctx.fill();ctx.strokeStyle='#c8b075';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(-12,0);ctx.lineTo(-23-swing*12,-15+swing*20);ctx.stroke();if(e.type==='captain'||champ){ctx.fillStyle='#d8a92e';ctx.fillRect(-17,-30,34,6)}if(champ){ctx.beginPath();ctx.moveTo(-16,-30);ctx.lineTo(-10,-43);ctx.lineTo(0,-31);ctx.lineTo(10,-43);ctx.lineTo(16,-30);ctx.fill()}if(e.striking){ctx.strokeStyle='#ff405d';ctx.lineWidth=5;ctx.globalAlpha=.65+.35*Math.sin(state.time*22);ctx.beginPath();ctx.arc(0,0,e.r+13,-Math.PI*.85,-Math.PI*.15);ctx.stroke();ctx.fillStyle='#ff405d';ctx.font='bold 18px Nunito';ctx.textAlign='center';ctx.fillText('!',0,-e.r-18);ctx.globalAlpha=1}ctx.restore();ctx.fillStyle='#130c1c';ctx.fillRect(e.x-20,e.y-e.r-17,40,4);ctx.fillStyle='#dc4761';ctx.fillRect(e.x-20,e.y-e.r-17,40*Math.max(0,e.hp/e.maxHp),4)}
  function drawGolem(g){ctx.save();const bob=g.moving?Math.abs(Math.sin(state.time*7))*5:0,step=g.moving?Math.sin(state.time*7)*5:0,slam=Math.min(1,g.attackAnim*5),rise=g.summon?g.summon*35:0;ctx.translate(g.x,g.y+bob+rise);if(g.summon){ctx.globalAlpha=1-g.summon*.8;ctx.strokeStyle='#b891ff';ctx.lineWidth=4;ctx.beginPath();ctx.arc(0,18,35*(1-g.summon),0,7);ctx.stroke()}ctx.fillStyle='#6e6278';ctx.fillRect(-20,-12,40,35);ctx.fillStyle='#93859c';ctx.beginPath();ctx.arc(0,-14,18,0,7);ctx.fill();ctx.fillStyle='#78dcff';ctx.fillRect(-9,-18,6,5);ctx.fillRect(4,-18,6,5);ctx.strokeStyle='#51465b';ctx.lineWidth=8;ctx.beginPath();ctx.moveTo(-20,0);ctx.lineTo(-31-step,16+slam*16);ctx.moveTo(20,0);ctx.lineTo(31+step,16+slam*16);ctx.moveTo(-10,20);ctx.lineTo(-12-step,31);ctx.moveTo(10,20);ctx.lineTo(12+step,31);ctx.stroke();ctx.globalAlpha=1;ctx.restore()}
  function drawEffect(v){ctx.save();ctx.translate(v.x,v.y);for(let i=0;i<4;i++){ctx.strokeStyle=`rgba(165,104,255,${.7-i*.12})`;ctx.lineWidth=5;ctx.beginPath();ctx.arc(0,0,v.r*(.25+i*.18),state.time*3+i,state.time*3+i+4.6);ctx.stroke()}ctx.restore()}
  function drawVine(v){if(v.points.length<2)return;ctx.save();ctx.lineCap='round';ctx.lineJoin='round';ctx.strokeStyle=v.hit?'#b7e58f':v.preview?'#8bd875aa':'#38753b';ctx.lineWidth=16;ctx.beginPath();ctx.moveTo(v.points[0].x,v.points[0].y);for(let i=1;i<v.points.length;i++)ctx.lineTo(v.points[i].x,v.points[i].y);ctx.stroke();ctx.strokeStyle='#79be58';ctx.lineWidth=4;ctx.stroke();for(let i=0;i<v.points.length;i+=2){const p=v.points[i];ctx.fillStyle='#9cdb68';ctx.beginPath();ctx.ellipse(p.x+8,p.y-5,9,4,(i%4)*.7,0,7);ctx.fill();ctx.fillStyle='#b7657b';ctx.beginPath();ctx.moveTo(p.x,p.y-8);ctx.lineTo(p.x+4,p.y-16);ctx.lineTo(p.x+8,p.y-7);ctx.fill()}if(!v.preview){ctx.fillStyle='#18331d';ctx.fillRect(v.points[0].x-18,v.points[0].y-25,36,4);ctx.fillStyle='#77cb61';ctx.fillRect(v.points[0].x-18,v.points[0].y-25,36*Math.max(0,v.hp/v.maxHp),4)}ctx.restore()}
  function drawSigil(x,y,r){ctx.save();ctx.translate(x,y);ctx.strokeStyle='#f5d36d';ctx.fillStyle='#f5d36d18';ctx.lineWidth=2;ctx.beginPath();ctx.arc(0,0,r,0,7);ctx.fill();ctx.stroke();ctx.rotate(state.time);for(let i=0;i<6;i++){ctx.rotate(Math.PI/3);ctx.beginPath();ctx.moveTo(r*.55,0);ctx.lineTo(r*.9,0);ctx.stroke()}ctx.restore()}
  function drawCharge(){const p=state.player,c=clamp(mouse.charge/1.15,0,1);ctx.strokeStyle=c>.75?'#ffd465':'#a78cff';ctx.lineWidth=4;ctx.beginPath();ctx.arc(p.x,p.y,30,-Math.PI/2,-Math.PI/2+c*Math.PI*2);ctx.stroke()}
  function loop(t){if(!state)return;const dt=Math.min(.033,(t-last)/1000);last=t;update(dt);draw();raf=requestAnimationFrame(loop)}
  function finish(title,copy,button,action){state.over=true;cancelFocus();$('#modal-title').textContent=title;$('#modal-copy').textContent=copy;$('#modal-button').textContent=button;$('#modal').classList.remove('hidden');$('#modal-button').onclick=()=>{$('#modal').classList.add('hidden');action()}}
  function defeat(){finish('The arena claims you',`You defeated ${state.kills} enemies and kept all XP earned. Gather your magic and try again.`,'Restart arena',start)}
  function victory(){addXP(150);finish('Arena conquered',`Ten rounds cleared · ${state.kills} enemies defeated · 150 bonus XP earned.`,'Return to sanctum',()=>{show('title');updateMeta()})}
  function togglePause(force){if(!state||state.over)return;state.paused=force===undefined?!state.paused:force;$('#pause-menu').classList.toggle('hidden',!state.paused);$('#pause-button').textContent=state.paused?'▶':'Ⅱ';if(state.paused)endShield()}
  function returnHome(){cancelAnimationFrame(raf);state=null;$('#pause-menu').classList.add('hidden');show('title');updateMeta()}
  $('#play-button').onclick=start;$('#talents-button').onclick=()=>{updateMeta();show('talents')};$('#back-button').onclick=()=>show('title');
  document.querySelectorAll('.arena-card').forEach(el=>el.onclick=()=>{selectedArena=el.dataset.arena;document.querySelectorAll('.arena-card').forEach(x=>x.classList.toggle('selected',x===el));$('#play-button').textContent=selectedArena==='colosseum'?'Enter the Colosseum':'Enter the Graveyard';tone(420,.08,'triangle')});
  document.querySelectorAll('.talent[data-talent]').forEach(el=>el.onclick=()=>{const k=el.dataset.talent;if(save.points>0&&save.talents[k]<3){save.points--;save.talents[k]++;persist();tone(620,.15,'triangle')}});
  document.querySelectorAll('.spell-talent').forEach(el=>el.onclick=()=>{const k=el.dataset.spellTalent;if(save.points>0&&save.spellTalents[k]<3){save.points--;save.spellTalents[k]++;persist();tone(690,.15,'triangle')}});
  $('#pause-button').onclick=()=>togglePause();$('#resume-button').onclick=()=>togglePause(false);$('#restart-button').onclick=()=>{$('#pause-menu').classList.add('hidden');start()};$('#home-button').onclick=returnHome;
  addEventListener('resize',resize);addEventListener('keydown',e=>{const first=!keys[e.code];keys[e.code]=true;if(!state||!screens.game.classList.contains('active'))return;if(e.code==='Escape'){if(state.focus)cancelFocus();else togglePause();return}if(state.paused)return;if(e.code==='Digit1')castFocus('golem');if(e.code==='Digit2')castFocus('vortex');if(e.code==='Digit3')castFocus('vines');if(e.code==='Digit4')castTeleport();if(e.code==='KeyQ'&&first)startShield()});addEventListener('keyup',e=>{keys[e.code]=false;if(e.code==='KeyQ')endShield()});
  canvas.addEventListener('mousemove',e=>{const r=canvas.getBoundingClientRect();mouse.x=e.clientX-r.left;mouse.y=e.clientY-r.top;if(mouse.vineDraw){const last=mouse.vineDraw[mouse.vineDraw.length-1];if(dist(last,mouse)>12&&mouse.vineDraw.length<40)mouse.vineDraw.push({x:mouse.x,y:mouse.y})}});canvas.addEventListener('mousedown',e=>{if(e.button===0){if(state.focus==='vines')mouse.vineDraw=[{x:mouse.x,y:mouse.y}];else if(state.focus)confirmFocus();else{mouse.down=true;mouse.charge=0}}});addEventListener('mouseup',e=>{if(e.button===0&&mouse.vineDraw){const points=mouse.vineDraw.slice();finishVines(points)}else if(e.button===0&&mouse.down){mouse.down=false;shoot();mouse.charge=0}});canvas.addEventListener('contextmenu',e=>{e.preventDefault();cancelFocus()});
  updateMeta();
})();
